### ISSUE TITLE
Error in MQTT reporting $METER_JSON

### ISSUE THREAD

**Issue by pascaltippelt** [weetmuts/wmbusmeters#847]
### Type of request

Bug

### HAOS version

[unsupportet on OpenMediaVault / Debian]

### wmbusmeters version

1.11.0

### Your message goes here

Hi!

I use wmbusmeters Home Assistant addon to read a heat cos allocator. But there seems to be a bug in the transmission of the $METER_JSON. My Configuration:

```yaml
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf: >-
  loglevel=debug\ndevice=auto:t1,c1\ndonotprobe=/dev/ttyAMA0\nlogtelegrams=false\nformat=json\nlogfile=/dev/stdout\nshell=/wmbusmeters/mosquitto_pub.sh
  wmbusmeters/$METER_ID $METER_JSON
meters:
  - |-
    name=ofen
    driver=bfw240radio
    id=00804410
    key=
mqtt:
  host: 192.168.178.200
  port: 1883
  user: CENSORED
  password: CENSORED
```
This works essentially (Debug):

```shell
(shell) exec "/bin/sh"
(shell) arg "-c"
(shell) arg "/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_ID \"$METER_JSON\""
(shell) env "METER_JSON={"media":"heat cost allocation","meter":"bfw240radio","name":"ofen","id":"00804410","current_hca":236,"prev_hca":845,"prev_01_hca":184,"prev_02_hca":845,"prev_03_hca":646,"prev_04_hca":517,"prev_05_hca":470,"prev_06_hca":467,"prev_07_hca":467,"prev_08_hca":467,"prev_09_hca":466,"prev_10_hca":443,"prev_11_hca":383,"prev_12_hca":280,"prev_13_hca":161,"prev_14_hca":403,"prev_15_hca":226,"prev_16_hca":69,"prev_17_hca":0,"prev_18_hca":0,"device_date":"2023-02-08","timestamp":"2023-02-08T18:44:21Z","device":"amb8465[00000000]","rssi_dbm":-57}"
```

But instead of

```json
{"media":"heat cost allocation","meter":"bfw240radio","name":"ofen","id":"00804410","current_hca":236,"prev_hca":845,"prev_01_hca":184,"prev_02_hca":845,"prev_03_hca":646,"prev_04_hca":517,"prev_05_hca":470,"prev_06_hca":467,"prev_07_hca":467,"prev_08_hca":467,"prev_09_hca":466,"prev_10_hca":443,"prev_11_hca":383,"prev_12_hca":280,"prev_13_hca":161,"prev_14_hca":403,"prev_15_hca":226,"prev_16_hca":69,"prev_17_hca":0,"prev_18_hca":0,"device_date":"2023-02-08","timestamp":"2023-02-08T18:44:21Z","device":"amb8465[00000000]","rssi_dbm":-57}
```

i only receive 

```raw
"{"media":"heat
```

in MQTT:

![grafik](https://user-images.githubusercontent.com/2066297/217624211-55b77282-c704-4c45-85b7-4b2dc6f57e16.png)

I do not understand, where I might did a misconfiguration and would be pleased, if you could help me resolve this problem.

If I use 

```yaml
conf: >-
  loglevel=debug\ndevice=auto:t1,c1\ndonotprobe=/dev/ttyAMA0\nlogtelegrams=false\nformat=json\nlogfile=/dev/stdout\nshell=/wmbusmeters/mosquitto_pub.sh
  wmbusmeters/$METER_ID $METER_CURRENT_HCA
```
instead, I can receive the $METER_CURRENT_HCA without problems.

I believe the " " (space) in heat cost allocation is the problem.

Best Pascal
