### ISSUE TITLE
Unable to set up multiple meters or documentation incorrect/inconsistent

### ISSUE THREAD

**Issue by convicte** [weetmuts/wmbusmeters#860]
### Type of request

Question

### HAOS version

2023.02.04

### wmbusmeters version

1.11.0-1

### Your message goes here

@KrzysztofHajdamowicz @BIBOLV 

Since you've worked together on https://github.com/weetmuts/wmbusmeters/pull/838 I allowed myself to seek your assistance:"

For the life of me I cannot create a correct configuration under the new scheme with two meters having `NOKEY`.
```yaml
data_path: /config/wmbusmeters
enable_mqtt_discovery: true
conf:
  loglevel: normal
  device: rtlwmbus:CMD(/usr/bin/nc -lku 9011)
  donotprobe: /dev/ttyUSB0
  logtelegrams: false
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"
  alarmshell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$ALARM_TYPE $ALARM_MESSAGE"
  meterfiles: /config/wmbusmeters/logs/meter_readings
  meterfilesaction: append
  meterfilesnaming: name
  meterfilestimestamp: day
  ignoreduplicates: true
  alarmexpectedactivity: mon-sun(00-23)
  alarmtimeout: 3h
meters:
  - name: water_meter
    driver: izar
    id: "4141d24a"
    key: "NOKEY"
  - name: garden_water_meter
    driver: izar
    id: 2141503d
    key: NOKEY
mqtt: {}
``` 
I've tried both with passing the `id` and `key` as string and not.
This is the exact layout indicated here: https://github.com/weetmuts/wmbusmeters/blob/master/ha-addon/DOCS.md

**Comment by convicte** [comment]
That's the error output:

```Failed to save add-on configuration, Invalid dict for option 'meters' in Wmbusmeters (W-MBus to MQTT) (cada3e3b_wmbusmeters). Got {'data_path': '/config/wmbusmeters', 'enable_mqtt_discovery': True, 'conf': {'loglevel': 'normal', 'device': 'rtlwmbus:CMD(/usr/bin/nc -lku 9011)', 'donotprobe': '/dev/ttyUSB0', 'logtelegrams': False, 'format': 'json', 'logfile': '/dev/stdout', 'shell': '/wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"', 'alarmshell': '/wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$ALARM_TYPE $ALARM_MESSAGE"', 'meterfiles': '/config/wmbusmeters/logs/meter_readings', 'meterfiles...
```

**Comment by BIBOLV** [comment]
Could you add quotation marks for id and key of second meter and try?
```
meters:
  - name: water_meter
    driver: izar
    id: "4141d24a"
    key: "NOKEY"
  - name: garden_water_meter
    driver: izar
    id: "2141503d"
    key: "NOKEY"
```

**Comment by convicte** [comment]
Tried all possible combinations! 
With and without on both and either - no dice.

**Comment by BIBOLV** [comment]
@KrzysztofHajdamowicz - what is your take on this issue?

**Comment by BIBOLV** [comment]
Found and started my dusty old test HA instance and my finding so far is that current config.json can work only with one meter.
When following config is used then there is no error and I could not find a way to add more:
```
meters:
  name: water_meter
  driver: izar
  id: 4141d24a
  key: NOKEY
```

**Comment by convicte** [comment]
Thank you for checking!

But I have to say that not exactly 'work' - because this https://github.com/weetmuts/wmbusmeters/issues/859

**Comment by KrzysztofHajdamowicz** [comment]
Ok, I analyzed config.json file and came to conclusion that schema has to change a little. `key` key has to be optional. I will figure out how to do it.

**Comment by BIBOLV** [comment]
@KrzysztofHajdamowicz - @thecem created PR https://github.com/weetmuts/wmbusmeters/pull/861 for this. Can you review and confirm that that would fix the issue?

**Comment by thecem** [comment]
@KrzysztofHajdamowicz if you add a "?" to "str" so "str?" will be an optional schema.

**Comment by BIBOLV** [comment]
Fix was pushed with https://github.com/weetmuts/wmbusmeters/pull/864 - please confirm that everything works now

**Comment by chpego** [comment]
> Fix was pushed with #864 - please confirm that everything works now

LGTM !

**Comment by casper255** [comment]
The latest version of the add-on is installed.  It is not possible to save the configuration with multiple meters.  Same message as above.

**Comment by chpego** [comment]
> The latest version of the add-on is installed. It is not possible to save the configuration with multiple meters. Same message as above.

can you post your configuration?

**Comment by casper255** [comment]
This is a working configuration on version 1.11.0

data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf: |-
  loglevel=normal
  device=auto:c1
  meterfiles=/config/wmbusmeters/logs/meter_readings/
  meterfilesaction=overwrite
  logtelegrams=true
  format=json
  logfile=/dev/stdout
  shell=/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:
  - |-
    name=grzejnik_salon_imp
    driver=fhkvdataiii
    id=05743828
  - |-
    name=grzejnik_kuchnia_imp
    driver=fhkvdataiii
    id=05743835
  - |-
    name=grzejnik_jadalnia_imp
    driver=fhkvdataiii
    id=05743829
  - |-
    name=grzejnik_julia_imp
    driver=fhkvdataiii
    id=05743794
  - |-
    name=grzejnik_sypialnia_imp
    driver=fhkvdataiii
    id=05743837
mqtt:
  host: 192.168.0.xxx
  port: 1883
  user: xxx
  password: xxx

The configuration I'm trying to save on version 1.11.0-2

data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
  loglevel: normal
  device: auto:c1
  meterfiles: /config/wmbusmeters/logs/meter_readings/
  meterfilesaction: overwrite
  logtelegrams: true
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:
  - name: grzejnik_salon_imp
    driver: fhkvdataiii
    id: 05743828
  - name: grzejnik_kuchnia_imp
    driver: fhkvdataiii
    id: 05743835
  - name: grzejnik_jadalnia_imp
    driver: fhkvdataiii
    id: 05743829
  - name: grzejnik_julia_imp
    driver: fhkvdataiii
    id: 05743794
  - name: grzejnik_sypialnia_imp
    driver: fhkvdataiii
    id: 05743837
mqtt:
  host: 192.168.0.xxx
  port: 1883
  user: xxx
  password: xxx

**Comment by thecem** [comment]
could you do us a favor and post it in correct way:

Mark the config
Click "<>"
Write after ''' YAML

```YAML
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
loglevel: normal
device: auto:c1
meterfiles: /config/wmbusmeters/logs/meter_readings/
meterfilesaction: overwrite
logtelegrams: true
format: json
logfile: /dev/stdout
shell: /wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:

    name: grzejnik_salon_imp
    driver: fhkvdataiii
    id: 05743828
    name: grzejnik_kuchnia_imp
    driver: fhkvdataiii
    id: 05743835
    name: grzejnik_jadalnia_imp
    driver: fhkvdataiii
    id: 05743829
    name: grzejnik_julia_imp
    driver: fhkvdataiii
    id: 05743794
    name: grzejnik_sypialnia_imp
    driver: fhkvdataiii
    id: 05743837
    mqtt:
    host: 192.168.0.xxx
    port: 1883
    user: xxx
    passwor
```d: xxx

**Comment by casper255** [comment]
```
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf: |-
  loglevel=normal
  device=auto:c1
  meterfiles=/config/wmbusmeters/logs/meter_readings/
  meterfilesaction=overwrite
  logtelegrams=true
  format=json
  logfile=/dev/stdout
  shell=/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:
  - |-
    name=grzejnik_salon_imp
    driver=fhkvdataiii
    id=05743828
  - |-
    name=grzejnik_kuchnia_imp
    driver=fhkvdataiii
    id=05743835
  - |-
    name=grzejnik_jadalnia_imp
    driver=fhkvdataiii
    id=05743829
  - |-
    name=grzejnik_julia_imp
    driver=fhkvdataiii
    id=05743794
  - |-
    name=grzejnik_sypialnia_imp
    driver=fhkvdataiii
    id=05743837
mqtt:
  host: 192.168.0.187
  port: 1883
  user: mqtt_user
  password: misiek255

```

**Comment by casper255** [comment]
```
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
  loglevel: normal
  device: auto:c1
  meterfiles: /config/wmbusmeters/logs/meter_readings/
  meterfilesaction: overwrite
  logtelegrams: true
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:
  - name: grzejnik_salon_imp
    driver: fhkvdataiii
    id: 05743828
  - name: grzejnik_kuchnia_imp
    driver: fhkvdataiii
    id: 05743835
  - name: grzejnik_jadalnia_imp
    driver: fhkvdataiii
    id: 05743829
  - name: grzejnik_julia_imp
    driver: fhkvdataiii
    id: 05743794
  - name: grzejnik_sypialnia_imp
    driver: fhkvdataiii
    id: 05743837
mqtt:
  host: 192.168.0.187
  port: 1883
  user: mqtt_user
  password: misiek255

```

**Comment by chpego** [comment]
> id: 05743829

you have to put double quotations for the id values

**Comment by convicte** [comment]
@casper255 
Are you certain this MQTT indent is working for you in 1.11.0? It looks to be set up incorrectly.

Also when you copy any code into git, please use three slashes ` before and after, to indicate to GIT it's code.
It will make it easier for people to help you.
You can also add the language after the slashes (like this 
![image](https://user-images.githubusercontent.com/78666770/219599816-797d13df-9bd9-4b2e-becd-4c3e7c82985f.png)
to make it even better).
It will result in this:
```yaml
YOUR CODE HERE
```

As for your config, please try this:

```yaml
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
   loglevel: normal
   device: auto:c1
   meterfiles: /config/wmbusmeters/logs/meter_readings/
   meterfilesaction: overwrite
   logtelegrams: true
   format: json
   logfile: /dev/stdout
   shell: /wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:
   name: grzejnik_salon_imp
   driver: fhkvdataiii
   id: "05743828"
   name: grzejnik_kuchnia_imp
   driver: fhkvdataiii
   id: "05743835"
   name: grzejnik_jadalnia_imp
   driver: fhkvdataiii
   id: "05743829"
   name: grzejnik_julia_imp
   driver: fhkvdataiii
   id: "05743794"
   name: grzejnik_sypialnia_imp
   driver: fhkvdataiii
   id: "05743837"
mqtt:
   host: 192.168.0.xxx
   port: 1883
   user: xxx
   password: xxx
 ```
In addition, if you are using Mosquito  you do not need to indicate the MQTT section just `{}` will be fine

**Comment by KrzysztofHajdamowicz** [comment]
> ```yaml
> meters:
>    name: grzejnik_salon_imp
>    driver: fhkvdataiii
>    id: "05743828"
>    name: grzejnik_kuchnia_imp
>    driver: fhkvdataiii
>    id: "05743835"
>    name: grzejnik_jadalnia_imp
>    driver: fhkvdataiii
>    id: "05743829"
>    name: grzejnik_julia_imp
>    driver: fhkvdataiii
>    id: "05743794"
>    name: grzejnik_sypialnia_imp
>    driver: fhkvdataiii
>    id: "05743837"
> mqtt:
>    host: 192.168.0.xxx
>    port: 1883
>    user: xxx
>    password: xxx
> ```

Correct format is:
```YAML
meters:
   - name: grzejnik_salon_imp
     driver: fhkvdataiii
     id: "05743828"
   - name: grzejnik_kuchnia_imp
     driver: fhkvdataiii
     id: "05743835"
   - name: grzejnik_jadalnia_imp
     driver: fhkvdataiii
     id: "05743829"
   - name: grzejnik_julia_imp
     driver: fhkvdataiii
     id: "05743794"
   - name: grzejnik_sypialnia_imp
     driver: fhkvdataiii
     id: "05743837"
```
