### ISSUE TITLE
Can't start bone stock HA add-on - Invalid list for option 'meters'...

### ISSUE THREAD

**Issue by mediaNen** [weetmuts/wmbusmeters#872]
**Type of request**
Bug

**HAOS version**
2023.02.05

**wmbusmeters version**
1.11.0-2

**Your message goes here:**
Installed the HA add-on from scratch, tried to start it up without changing anything - it gives the following error:
Invalid list for option 'meters' in Wmbusmeters (W-MBus to MQTT) (cada3e3b_wmbusmeters). (I get the option to go to the config tile where it shows the errors in greater detail when editing something and clicking save):

"Failed to save add-on configuration, Invalid list for option 'meters' in Wmbusmeters (W-MBus to MQTT) (cada3e3b_wmbusmeters). Got {'data_path': '/config/wmbusmeters', 'enable_mqtt_discovery': False, 'conf': {'loglevel': 'normal', 'device': 'auto:t1:c1', 'donotprobe': '/dev/ttyAMA0', 'logtelegrams': False, 'format': 'json', 'logfile': '/dev/stdout', 'shell': '/wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"'}, 'meters': {'name': 'ElectricityMeter', 'driver': 'amiplus', 'id': '12345678', 'key': 'DEADBEEF1337DEADBEEF1337DEADBEEF'}, 'mqtt': {}}"

I have used this up till today on my RPI4 without any issues, but when I moved to a freshly installed VM the newly installed add-on will not start. I was using an older version of the wmbusmeters add-on which I guess is why it worked on the RPI4.

**Comment by BIBOLV** [comment]
Configuration has changed in latest version - please check docs. 
If you can`t find where the issue is - post config here.

**Comment by mediaNen** [comment]
It is setup with the new configuration - bone stock :)
The config is in yaml:

data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
  loglevel: normal
  device: auto:t1
  donotprobe: /dev/ttyAMA0
  logtelegrams: false
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"
meters:
  name: ElectricityMeter
  driver: amiplus
  id: "12345678"
  key: DEADBEEF1337DEADBEEF1337DEADBEEF
mqtt: {}

![Screenshot 2023-02-17 222152](https://user-images.githubusercontent.com/115061247/219796002-fa37c7cd-adc3-45ef-9bcd-ed938fad9d3a.png)

**Comment by BIBOLV** [comment]
And what config gives you error?

**Comment by mediaNen** [comment]
I am not sure, I can't find any library in config or ect folder in HA. Forgive me for beeing a newbie here.
Do I manually have to add files to the /config/ folder?
![Screenshot 2023-02-17 223214](https://user-images.githubusercontent.com/115061247/219797792-7662f288-b0c6-4290-9de6-75876d856273.png)

**Comment by BIBOLV** [comment]
What config do you have on old instance, I guess you want to transfer it, or want to start from scratch?

**Comment by mediaNen** [comment]
I guess I would rather start from scratch.
The old config was like this:

|-
  loglevel=normal
  device=im871a:c1,t1
  donotprobe=/dev/ttyAMA0
  logtelegrams=true
  format=json
  logfile=/dev/stdout
  shell=/wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"

- |-
  name=WaterSensor
  driver=multical21
  id=76791307
  key=8EF8FAEC2103F0BECFA1487XXXXXXXX

I do not have a wmbusmeters folder under the /config/ folder - I had on my old PI4.

**Comment by BIBOLV** [comment]
Try following, this should have you started:
```yaml
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
  loglevel: normal
  device: im871a:c1,t1
  donotprobe: /dev/ttyAMA0
  logtelegrams: true
  format: json
  logfile: /dev/stdout
  shell: wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
meters:
  - name: WaterSensor
    driver: multical21
    id: "76791307"
    key: 8EF8FAEC2103F0BECFA1487XXXXXXXX
mqtt: {}

```
