### ISSUE TITLE
Can not save config and run addon

### ISSUE THREAD

**Issue by pepsonEL** [weetmuts/wmbusmeters#874]
### Type of request

Enhancement

### HAOS version

HassOS 9.5

### wmbusmeters version

1.11.0-2 

### Your message goes here

Hi
I installed wmbus addon and connect by USB adapter with radio. I create config and try save it and run addon but i can not:

```
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
  loglevel: normal
  device: auto:t1
  donotprobe: /dev/ttyUSB1
  logtelegrams: false
  format: json
  logfile: /dev/stdout
  shell: /wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"
meters:
  name: WaterMeter
  driver: apator162
  id: "00068526"
  key: 00000000000000000000000000000000
mqtt:
  host: 192.168.10.3
  port: 1883
  user: MyUser
  password: MyPassowrd
```

i get this error when try save:

Nie udało się zapisać konfiguracji dodatku, Invalid list for option 'meters' in Wmbusmeters (W-MBus to MQTT) (cada3e3b_wmbusmeters). Got {'data_path': '/config/wmbusmeters', 'enable_mqtt_discovery': False, 'conf': {'loglevel': 'normal', 'device': 'auto:t1', 'donotprobe': '/dev/ttyUSB1', 'logtelegrams': False, 'format': 'json', 'logfile': '/dev/stdout', 'shell': '/wmbusmeters/mosquitto_pub.sh "wmbusmeters/$METER_NAME" "$METER_JSON"'}, 'meters': {'name': 'WaterMeter', 'driver': 'apator162', 'id': '00068526', 'key': 0}, 'mqtt': {'host': '192.168.10.3', 'port': 1883, 'user': 'MyUser', 'password': 'MyPassword'}}

**Comment by thecem** [comment]
Meters needs an array:

```YAML
meters:
  - name: WaterMeter
     driver: apator162
     id: "00068526"
     key: 00000000000000000000000000000000
```

**Comment by pepsonEL** [comment]
What you mean ?

**Comment by thecem** [comment]
Put my example, in your config. With hyphen

**Comment by pepsonEL** [comment]
What example ?

**Comment by thecem** [comment]
![199D8861-A221-4C23-B1F7-1A17BD5299A9](https://user-images.githubusercontent.com/46648579/219944902-db0954e4-bc9a-4e38-a8c5-f37a8eb5db7b.jpeg)

**Comment by pepsonEL** [comment]
ok i change
```
meters:
  - name: WaterMeter
    driver: apator162
    id: "00068526"
    key: 00000000000000000000000000000000
```

and also can not save
