### ISSUE TITLE
Sensus iPerl

### ISSUE THREAD

**Issue by Murcin86** [weetmuts/wmbusmeters#878]
### Type of request

Question

### OS version

HomeAssistant 2023.2.5

### wmbusmeters version

1.11.0-2

### Your message goes here

hi !
I`ve got information from local water supplier about encription key for water sensor and they told me that there is no any key or password need it because communication is open 

I with new version of wmbusmeters I decide to check... but got problem with telegram... maybe that`s not a bug but wrong interpretation of telegram (json?)

> (serial) received ascii "T1;1;1;2023-02-21 21:10:18.000;28;27;20847864;0x1e44ae4c6478842068077a89001005c6fd4faa63f85837e5cc1b3ec6d0db3b<0A>"
> (rtlwmbus) checkRTLWMBusFrame "T1;1;1;2023-02-21 21:10:18.000;28;27;20847864;0x1e44ae4c6478842068077a89001005c6fd4faa63f85837e5cc1b3ec6d0db3b<0A>"
> (rtlwmbus) received full frame
> (wmbus) parseDLL @0 31
> (wmbus) parseELL @10 21
> (wmbus) parseNWL @10 21
> (wmbus) parseAFL @10 21
> (wmbus) parseTPL @10 21
> (meter) wodomierz: for me? 20847864 in 20847864
> (meter) wodomierz: yes for me
> (meter) wodomierz(1) iperl  handling telegram from 20847864
> (meter) wodomierz 20847864 "1E44AE4C6478842068077A89001005C6FD4FAA63F85837E5CC1B3EC6D0DB3B"
> (wmbus) parseDLL @0 31
> (telegram) DLL L=1e C=44 (from meter SND_NR) M=4cae (SEN) A=20847864 VER=68 TYPE=07 (Water meter) (driver iperl) DEV=rtlwmbus[00000001] RSSI=28
> (wmbus) parseELL @10 21
> (wmbus) parseNWL @10 21
> (wmbus) parseAFL @10 21
> (wmbus) parseTPL @10 21
> (TPL) num encrypted blocks 1 (16 bytes and remaining unencrypted 0 bytes)
> (wmbus) WARNING! no key to decrypt payload! Permanently ignoring telegrams from id: 20847864 mfct: (SEN) Sensus Metering Systems, Germany (0x4cae) type: Water meter (0x07) ver: 0x68
> (telegram) TPL CI=7a ACC=89 STS=00 CFG=0510 (AES_CBC_IV nb=1 cntn=0 ra=0 hc=0)
> (wmbus) telegram from 20847864 ignored by all configured meters!
> (main) rtlsdr device  not currently used.
> (main) found specified device (rtlwmbus:868.9M:t1) that matches detected device (:rtlwmbus[]:0/0)
> (main) opening rtlwmbus:868.9M:t1
> Started config rtlwmbus listening on t1 using fq 868.9M
> (rtlwmbus) using command: /usr/bin/rtl_sdr  -d -1 -f 868.9M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus
> (rtlwmbus) opening 
> (bgshell) exec background "/bin/sh"
> (serial) EVENT thread interrupted
> (bgshell) arg "-c"
> (bgshell) arg "/usr/bin/rtl_sdr  -d -1 -f 868.9M -s 1.6e6 - 2>/dev/null | /usr/bin/rtl_wmbus"
> (serialcmd) opened /bin/sh pid 129879 fd 7 (rtlwmbus)
> (main) regular reset of rtlwmbus  will happen every 82800 seconds
> (wmbus) no alarm (expected activity) for rtlwmbus
> (serial) TIMER thread interrupted
> (serial) EVENT thread interrupted
> (bgshell) 129879 exited with return code 0
> (serial) closing non working fd=7 ""
> (wmbus) disconnected  rtlwmbus
> (serialcmd) closed /bin/sh pid=129879 fd=7 (rtlwmbus)
> Lost  closing rtlwmbus
> (wmbus) closing....
> (wmbus) deleted rtlwmbus
> (serialcmd) closed /bin/sh pid=129879 fd=-1 (rtlwmbus)
> (serial) EVENT thread interrupted

here is my configuration:

```
data_path: /config/wmbusmeters
enable_mqtt_discovery: false
conf:
  loglevel: debug
  device: rtlwmbus:868.9M:t1
  donotprobe: all
  logtelegrams: true
  format: json
  logfile: /config/wmbusmeters/wmbusmeters.log
  shell: /wmbusmeters/mosquitto_pub.sh wmbusmeters/$METER_NAME "$METER_JSON"
  meterfiles: /config/wmbusmeters/logs/meter_readings/
meters:
  - name: wodomierz
    driver: iperl
    id: "20847864"
mqtt: {}
```
